[project]
name = "resources"
version = "0.1.0"
description = "documentation_ai using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.13"
dependencies = [
    "crewai[tools]>=0.118.0,<1.0.0",
    "langchain-google-genai>=0.0.5",
    "openai>=1.0.0",
    "dedent (>=0.5,<0.6)"
]

[project.scripts]
documentation_ai = "resources.main:run"
run_crew = "resources.main:run"
train = "resources.main:train"
replay = "resources.main:replay"
test = "resources.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
